/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controler.MyError;
import Model.Click;
import Model.MouseControl;
import Model.TransparentBackground;
import java.awt.Color;
import java.awt.Point;
import java.awt.Robot;
import static java.lang.Math.random;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author FerminMF
 */
public class EditClickFrame extends javax.swing.JFrame {

    /**
     * Creates new form EditClickFrame
     */
    private Click k = new Click();
    private String aliasClickPrime;
    private JTable tablaClicks;
    private boolean location = false;

    public EditClickFrame(JTable j) {
        initComponents();
        this.setVisible(true);
        tablaClicks = j;
        this.getContentPane().setBackground(Color.WHITE);
        jpEncabezado.setBackground(Color.WHITE);
        jPanel1.setBackground(Color.WHITE);
        establecerClicks();
    }

    public void establecerClicks() {
        DefaultComboBoxModel z = (DefaultComboBoxModel) jcClicks.getModel();
        Iterator<Click> j = MouseControl.getConjuntoClicks().iterator();
        while (j.hasNext()) {
            Click h = j.next();
            z.addElement(h.getAlias());
        }

    }

    public void establecerClick1(Click e, boolean corde) {
        aliasClickPrime = e.getAlias();
        if (corde) {

            if (e.isEsCuadrado()) {
                jlequisPosicion.setText((e.getCoordenadasClick()[3] - e.getCoordenadasClick()[2]) + "-" + e.getCoordenadasClick()[3]);
                jlyposicion.setText(e.getCoordenadasClick()[1] - e.getCoordenadasClick()[0] + "-" + e.getCoordenadasClick()[1]);
            } else {
                jlequisPosicion.setText(e.getX() + "");
                jlyposicion.setText(e.getY() + "");
            }
        } else {

            jtAliasClick.setText(e.getAlias());
            if (e.isRandom()) {
                jcUseAlea.setSelected(true);
                jtSegundosClicks.setEnabled(false);
                jtAleaUno.setEnabled(true);
                jtAleaDos.setEnabled(true);
                jtSegundosClicks.setText("");
                jtAleaUno.setText(e.getRandomuno() / 1000 + "");
                jtAleaDos.setText(e.getRandomdos() / 1000 + "");

            } else {
                jtSegundosClicks.setEnabled(true);
                jtAleaUno.setText("");
                jtAleaUno.setEnabled(false);
                jtAleaDos.setText("");
                jtAleaDos.setEnabled(false);
                jtSegundosClicks.setText(e.getDuracionClick() / 1000 + "");
            }
            if (e.isDoble()) {
                dobleClick.setSelected(true);
            }
            if (e.isEsCuadrado()) {
                jlequisPosicion.setText((e.getCoordenadasClick()[3] - e.getCoordenadasClick()[2]) + "-" + e.getCoordenadasClick()[3]);
                jlyposicion.setText(e.getCoordenadasClick()[1] - e.getCoordenadasClick()[0] + "-" + e.getCoordenadasClick()[1]);
            } else {
                jlequisPosicion.setText(e.getX() + "");
                jlyposicion.setText(e.getY() + "");
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpEncabezado = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jcClicks = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtAliasClick = new javax.swing.JTextField();
        jtSegundosClicks = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtAleaUno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtAleaDos = new javax.swing.JTextField();
        jcUseAlea = new javax.swing.JCheckBox();
        andirPosicion = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jlequisPosicion = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlyposicion = new javax.swing.JLabel();
        jcEstablecerr = new javax.swing.JCheckBox();
        dobleClick = new javax.swing.JCheckBox();
        jbSalir = new javax.swing.JButton();
        jbAceptarCambio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/catpawn.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 48)); // NOI18N
        jLabel3.setText("Cursore");

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 48)); // NOI18N
        jLabel2.setText("v2.1");

        javax.swing.GroupLayout jpEncabezadoLayout = new javax.swing.GroupLayout(jpEncabezado);
        jpEncabezado.setLayout(jpEncabezadoLayout);
        jpEncabezadoLayout.setHorizontalGroup(
            jpEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEncabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jpEncabezadoLayout.setVerticalGroup(
            jpEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEncabezadoLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpEncabezadoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jcClicks.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        jcClicks.setMaximumRowCount(200);
        jcClicks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcClicksActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        jLabel1.setText("Alias del click");

        jLabel5.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        jLabel5.setText("Segundos del click");

        jtAliasClick.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N

        jtSegundosClicks.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        jLabel6.setText("Aleatorio entre:");

        jtAleaUno.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        jLabel7.setText("y");

        jtAleaDos.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N

        jcUseAlea.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        jcUseAlea.setText("Utilizar");
        jcUseAlea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcUseAleaActionPerformed(evt);
            }
        });

        andirPosicion.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        andirPosicion.setText("Asignar nueva Posicion");
        andirPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andirPosicionActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jLabel8.setText("X");

        jlequisPosicion.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jLabel9.setText("Y");

        jlyposicion.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N

        jcEstablecerr.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jcEstablecerr.setText("Click aleatorio en una zona");
        jcEstablecerr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcEstablecerrActionPerformed(evt);
            }
        });

        dobleClick.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        dobleClick.setText("Doble Click");

        jbSalir.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(39, 39, 39)
                        .addComponent(jtAleaUno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtAleaDos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcUseAlea, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtAliasClick)
                            .addComponent(jtSegundosClicks)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jcClicks, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dobleClick)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(andirPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcEstablecerr, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 7, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jlequisPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlyposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcClicks, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSalir))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtAliasClick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jtSegundosClicks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtAleaUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jtAleaDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcUseAlea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dobleClick)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlequisPosicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlyposicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(andirPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcEstablecerr)
                .addGap(23, 23, 23))
        );

        jbAceptarCambio.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jbAceptarCambio.setText("Aceptar Cambios");
        jbAceptarCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarCambioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpEncabezado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbAceptarCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAceptarCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void andirPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andirPosicionActionPerformed
        MouseControl mouse = new MouseControl();
        JFrame g = this;
        k.setEsCuadrado(false);
        Thread z = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    if (jcEstablecerr.isSelected()) {
                        TransparentBackground.iniciarCaptura();
                        location = true;
                        Robot e = new Robot();
                        while (TransparentBackground.isTeste()) {
                            e.delay(1000);
                        }
                        TransparentBackground.setTeste(true);
                        k.setEsCuadrado(true);
                        k.setCoordenadasClick(TransparentBackground.getCoordenadasPasar());
                        k.setCoordenadas(TransparentBackground.coordenadas);
                        establecerClick1(k, true);
                    } else {
                        Point actualPosi = mouse.devolverPosicion();
                        k.setLocation(actualPosi);
                        establecerClick1(k, true);
                        location = false;
                    }

                } catch (InterruptedException ex) {
                    VentanaNotificaciones.ventanaError("Se ha detenido la ejecución", g);
                } catch (Exception ex) {
                    VentanaNotificaciones.ventanaError("Error inesperado" + ex.getMessage(), g);
                }
            }
        }, "AnadirPoss");
        z.start();

    }//GEN-LAST:event_andirPosicionActionPerformed

    private void jcClicksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcClicksActionPerformed
        // TODO add your handling code here:
        Iterator<Click> h = MouseControl.getConjuntoClicks().iterator();
        while (h.hasNext()) {
            Click z = h.next();
            if (z.getAlias().equalsIgnoreCase(jcClicks.getSelectedItem() + "")) {
                establecerClick1(z, false);
            }
        }


    }//GEN-LAST:event_jcClicksActionPerformed

    private void jcEstablecerrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcEstablecerrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcEstablecerrActionPerformed

    private void jcUseAleaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcUseAleaActionPerformed
        // TODO add your handling code here:
        if (jcUseAlea.isSelected()) {
            jtSegundosClicks.setEnabled(false);
            jtAleaUno.setEnabled(true);
            jtAleaDos.setEnabled(true);
            jtSegundosClicks.setText("");
        } else {
            jtSegundosClicks.setEnabled(true);
            jtAleaUno.setText("");
            jtAleaUno.setEnabled(false);
            jtAleaDos.setText("");
            jtAleaDos.setEnabled(false);
        }
    }//GEN-LAST:event_jcUseAleaActionPerformed

    private void jbAceptarCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarCambioActionPerformed
        try {
            // TODO add your handling code here:
            if (MouseControl.getConjuntoClicks().isEmpty()) {
                VentanaNotificaciones.ventanaError("No hay clicks a editar", this);
            } else {
                String esco = jcClicks.getSelectedItem() + "";
                for (int i = 0; i < MouseControl.getConjuntoClicks().size(); i++) {
                    if (MouseControl.getConjuntoClicks().get(i).getAlias().equalsIgnoreCase(esco)) {
                        Click used = MouseControl.getConjuntoClicks().get(i);
                        if (location) {
                            used.setCoordenadasClick(k.getCoordenadasClick());
                            used.setCoordenadas(k.getCoordenadas());
                            used.setEsCuadrado(true);
                        } else {
                            if (!used.isEsCuadrado()) {
                                used.setEsCuadrado(false);
                                used.setLocation(new Point((int) Double.parseDouble(jlequisPosicion.getText()), (int) Double.parseDouble(jlyposicion.getText())));

                            }

                        }
                        if (!used.getAlias().equalsIgnoreCase(jtAliasClick.getText()) && !MouseControl.aliasRepetido(jtAliasClick.getText())) {
                            used.setAlias(jtAliasClick.getText());
                        }
                        if (jcUseAlea.isSelected()) {
                            used.setRandom(true);
                            used.setRandomuno(Integer.parseInt(jtAleaUno.getText()) * 1000);
                            used.setRandomdos(Integer.parseInt(jtAleaDos.getText()) * 1000);
                        } else {
                            used.setRandom(false);
                            if (jtSegundosClicks.getText().isEmpty()) {
                                used.setDuracionClick(1600);
                            } else {
                                used.setDuracionClick(Integer.parseInt(jtSegundosClicks.getText()) * 1000);
                            }
                        }
                        if (dobleClick.isSelected()) {
                            used.setDoble(true);
                        } else {
                            used.setDoble(false);
                        }
                    }
                }

                // Cambiar que esto da sida
                DefaultComboBoxModel p = (DefaultComboBoxModel) jcClicks.getModel();
                p.removeAllElements();
                establecerClicks();
                MouseControl.actualizarTabla(tablaClicks);
            }

        } catch (Exception ex) {
            VentanaNotificaciones.ventanaError(ex.getMessage(), this);
        }
    }//GEN-LAST:event_jbAceptarCambioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton andirPosicion;
    private javax.swing.JCheckBox dobleClick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAceptarCambio;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<String> jcClicks;
    private javax.swing.JCheckBox jcEstablecerr;
    private javax.swing.JCheckBox jcUseAlea;
    private javax.swing.JLabel jlequisPosicion;
    private javax.swing.JLabel jlyposicion;
    private javax.swing.JPanel jpEncabezado;
    private javax.swing.JTextField jtAleaDos;
    private javax.swing.JTextField jtAleaUno;
    private javax.swing.JTextField jtAliasClick;
    private javax.swing.JTextField jtSegundosClicks;
    // End of variables declaration//GEN-END:variables

}
