/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controler.MyError;
import Model.GestorJSON;
import Model.GestorXML;
import javax.swing.JTable;

/**
 *
 * @author fer
 */
public class FileImport extends javax.swing.JFrame {

    /**
     * Creates new form FilechoserImport
     */
    public MainFrame e;
    public FileImport(MainFrame e) {
        initComponents();
        this.e = e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfimport = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jfimport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfimportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jfimport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jfimport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jfimportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfimportActionPerformed
        // TODO add your handling code here:

        if (evt.getActionCommand().equalsIgnoreCase("CancelSelection")) {
            this.setVisible(false);
        } else if (evt.getActionCommand().equalsIgnoreCase("ApproveSelection")) {
            try {
                GestorJSON.leerJSON(jfimport.getSelectedFile() + "",e);
                this.setVisible(false);
            } catch (Exception ex) {
                VentanaNotificaciones.ventanaError(ex.getMessage(), this);
            }
        }
    }//GEN-LAST:event_jfimportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jfimport;
    // End of variables declaration//GEN-END:variables
}
