/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controler.MyError;
import Model.GestorJSON;
import Model.GestorXML;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author fer
 */
public class FileExport extends javax.swing.JFrame {

    /**
     * Creates new form FileChoser
     */
    private String type;

    public FileExport(String type) {
        initComponents();
        this.type = type;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jxmlChoser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jxmlChoser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jxmlChoser.setApproveButtonText("Guardar");
        jxmlChoser.setApproveButtonToolTipText("");
        jxmlChoser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxmlChoserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jxmlChoser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jxmlChoser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jxmlChoserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxmlChoserActionPerformed

        if (evt.getActionCommand().equalsIgnoreCase("CancelSelection")) {
            this.setVisible(false);
        } else if (evt.getActionCommand().equalsIgnoreCase("ApproveSelection")) {
            try {
                if (type.equalsIgnoreCase("XML")) {
                    GestorXML.escribirDocumento(jxmlChoser.getSelectedFile() + "");
                    this.setVisible(false);
                } else if (type.equalsIgnoreCase("JSON")) {
                    GestorJSON.escribirJson(jxmlChoser.getSelectedFile() + "");
                    this.setVisible(false);
                }

            } catch (MyError ex) {
                VentanaNotificaciones.ventanaError(ex.getMessage(), this);
            }
        }
    }//GEN-LAST:event_jxmlChoserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jxmlChoser;
    // End of variables declaration//GEN-END:variables
}
